# This is a basic workflow to help you get started with Actions
name: Public Ranking Action

description: 'Call Score API'
inputs:
  other_repo:  # id of input
    description: 'ScoreBoard Repo'
    required: true
  public_name:
    required: true
  public_author:
    required: true
  pat: # id of input
    description: 'Personal Access Token'
    required: true
  name: # id of input
    description: 'Other Name'
    required: true
  repo: # id of input
    description: 'Other Repo Name'
    required: true
  author: # id of input
    description: 'Author Email'
    required: true
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.other_repo }}

