# This is a basic workflow to help you get started with Actions
name: Public Ranking Action

description: 'Call Score API'
inputs:
  public_repo:  # id of input
    description: 'ScoreBoard Repo'
    required: true
  public_name:
    required: true
  public_author:
    required: true
  private_repo: # id of input
    description: 'Other Name'
    required: true
  private_name: # id of input
    description: 'Other Repo Name'
    required: true
  private_author: # id of input
    description: 'Author Email'
    required: true
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.public_repo }}
    - ${{ inputs.public_name }}
    - ${{ inputs.public_author }}
    - ${{ inputs.private_repo }}
    - ${{ inputs.private_name }}
    - ${{ inputs.private_author }}

